//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLogin
    {
        public decimal Admin_Id { get; set; }
        public decimal Admin_AdminTypeId { get; set; }
        public string Admin_UserName { get; set; }
        public string Admin_Password { get; set; }
        public bool Admin_Status { get; set; }
    
        public virtual AdminType AdminType { get; set; }
    }
}
