//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.ContactInformations = new HashSet<ContactInformation>();
        }
    
        public decimal City_Id { get; set; }
        public decimal City_StateId { get; set; }
        public string City_Name { get; set; }
        public bool City_Status { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<ContactInformation> ContactInformations { get; set; }
    }
}
