//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInformation
    {
        public decimal ContactInformation_Id { get; set; }
        public decimal ContactInformation_RegistrationId { get; set; }
        public decimal ContactInformation_StateId { get; set; }
        public decimal ContactInformation_CityId { get; set; }
        public string ContactInformation_Address { get; set; }
        public string ContactInformation_MobileNo { get; set; }
        public string ContactInformation_AlternateMobileNo { get; set; }
        public string ContactInformation_EmailId { get; set; }
    
        public virtual City City { get; set; }
        public virtual State State { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
