//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public Designation()
        {
            this.JobOpenings = new HashSet<JobOpening>();
        }
    
        public decimal Designation_Id { get; set; }
        public string Designation_Qualification { get; set; }
        public string Designation_Name { get; set; }
        public string Designation_KeySkillDescription { get; set; }
        public bool Designation_Status { get; set; }
    
        public virtual ICollection<JobOpening> JobOpenings { get; set; }
    }
}
