//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationCategory
    {
        public EducationCategory()
        {
            this.EducationSubTypes = new HashSet<EducationSubType>();
            this.EducationTypes = new HashSet<EducationType>();
            this.Qualifications = new HashSet<Qualification>();
        }
    
        public decimal Education_CategoryId { get; set; }
        public string Education_CategoryName { get; set; }
        public bool Education_CategoryStatus { get; set; }
    
        public virtual ICollection<EducationSubType> EducationSubTypes { get; set; }
        public virtual ICollection<EducationType> EducationTypes { get; set; }
        public virtual ICollection<Qualification> Qualifications { get; set; }
    }
}
