//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationType
    {
        public EducationType()
        {
            this.EducationSubTypes = new HashSet<EducationSubType>();
            this.Qualifications = new HashSet<Qualification>();
        }
    
        public decimal EducationType_Id { get; set; }
        public decimal EducationType_EducationCategoryId { get; set; }
        public string EducationType_Name { get; set; }
        public bool EducationType_Status { get; set; }
    
        public virtual EducationCategory EducationCategory { get; set; }
        public virtual ICollection<EducationSubType> EducationSubTypes { get; set; }
        public virtual ICollection<Qualification> Qualifications { get; set; }
    }
}
