//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationSubType
    {
        public EducationSubType()
        {
            this.Qualifications = new HashSet<Qualification>();
        }
    
        public decimal EducationSubType_Id { get; set; }
        public decimal EducationSubType_EducationCategoryId { get; set; }
        public decimal EducationSubType_EducationTypeId { get; set; }
        public string EducationSubType_Name { get; set; }
        public bool EducationSubType_Status { get; set; }
    
        public virtual EducationCategory EducationCategory { get; set; }
        public virtual EducationType EducationType { get; set; }
        public virtual ICollection<Qualification> Qualifications { get; set; }
    }
}
