//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public decimal FeedBack_Id { get; set; }
        public string FeedBack_Emaill { get; set; }
        public string Feedback_Message { get; set; }
    }
}
