//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalDisqualification
    {
        public decimal FinalDisqualification_Id { get; set; }
        public decimal FinalDisqualification_JobAppliedId { get; set; }
        public decimal FinalDisqualification_RoundId { get; set; }
        public string FinalDisqualification_Remarks { get; set; }
    
        public virtual InterViewRound InterViewRound { get; set; }
        public virtual JobApplied JobApplied { get; set; }
    }
}
