//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalSelection
    {
        public decimal FinalSelection_Id { get; set; }
        public decimal FinalSelection_JobAppliedId { get; set; }
        public decimal FinalSelection_RoundId { get; set; }
        public int FinalSelection_SalaryOffered { get; set; }
        public System.DateTime FinalSelection_JoiningDate { get; set; }
        public string FinalSelection_ProbationPeriod { get; set; }
    
        public virtual InterViewRound InterViewRound { get; set; }
        public virtual JobApplied JobApplied { get; set; }
    }
}
