//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterViewRound
    {
        public InterViewRound()
        {
            this.FinalDisqualifications = new HashSet<FinalDisqualification>();
            this.FinalSelections = new HashSet<FinalSelection>();
        }
    
        public decimal InterviewRounds_Id { get; set; }
        public string Round_Name { get; set; }
        public bool Round_Status { get; set; }
    
        public virtual ICollection<FinalDisqualification> FinalDisqualifications { get; set; }
        public virtual ICollection<FinalSelection> FinalSelections { get; set; }
    }
}
