//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplied
    {
        public JobApplied()
        {
            this.FinalDisqualifications = new HashSet<FinalDisqualification>();
            this.FinalSelections = new HashSet<FinalSelection>();
        }
    
        public decimal JobApplied_Id { get; set; }
        public decimal JobApplied_JobOpenings_Id { get; set; }
        public decimal JobApplied_RegisterationId { get; set; }
        public System.DateTime JobApplied_ApplyDate { get; set; }
        public string JobApplied_Status { get; set; }
    
        public virtual ICollection<FinalDisqualification> FinalDisqualifications { get; set; }
        public virtual ICollection<FinalSelection> FinalSelections { get; set; }
        public virtual JobOpening JobOpening { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
