//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOpening
    {
        public JobOpening()
        {
            this.JobApplieds = new HashSet<JobApplied>();
        }
    
        public decimal JobOpenings_Id { get; set; }
        public decimal JobOpenings_DesignationId { get; set; }
        public string JobOpenings_JobType { get; set; }
        public string JobOpenings_Vaccancies { get; set; }
        public string JobOpenings_Location { get; set; }
        public string JobOpenings_WorkExperience { get; set; }
        public System.DateTime JobOpenings_PostDateTime { get; set; }
        public string JobOpenings_Title { get; set; }
        public string JobOpening_InterviewVenue { get; set; }
        public System.DateTime JobOpenings_InterviewDate { get; set; }
        public bool JobOpenings_Status { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual ICollection<JobApplied> JobApplieds { get; set; }
    }
}
