//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInformation
    {
        public decimal PersonalInformation_Id { get; set; }
        public decimal PersonalInformation_RegistrationId { get; set; }
        public string PersonalInformation_FirstName { get; set; }
        public string PersonalInformation_LastName { get; set; }
        public string PersonalInformation_DateOfBirth { get; set; }
        public string PersonalInformation_Gender { get; set; }
        public string PersonalInformation_MaritialStatus { get; set; }
    
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
