//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public decimal Qualification_Id { get; set; }
        public decimal Qualification_RegistrationId { get; set; }
        public decimal Qualification_EducationCategoryId { get; set; }
        public decimal Qualification_EducationTypeId { get; set; }
        public decimal Qualification_EducationSubTypeId { get; set; }
        public string Qualification_BoardUniversity { get; set; }
        public int Qualification_PassingYear { get; set; }
        public int Qualification_Percentage { get; set; }
    
        public virtual EducationCategory EducationCategory { get; set; }
        public virtual EducationSubType EducationSubType { get; set; }
        public virtual EducationType EducationType { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
