//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecruitmentZoneEntities : DbContext
    {
        public RecruitmentZoneEntities()
            : base("name=RecruitmentZoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<AdminType> AdminTypes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ContactInformation> ContactInformations { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<EducationCategory> EducationCategories { get; set; }
        public virtual DbSet<EducationSubType> EducationSubTypes { get; set; }
        public virtual DbSet<EducationType> EducationTypes { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<FinalDisqualification> FinalDisqualifications { get; set; }
        public virtual DbSet<FinalSelection> FinalSelections { get; set; }
        public virtual DbSet<InterViewRound> InterViewRounds { get; set; }
        public virtual DbSet<JobApplied> JobApplieds { get; set; }
        public virtual DbSet<JobOpening> JobOpenings { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
        public virtual DbSet<WorkExperience> WorkExperiences { get; set; }
        public virtual DbSet<PersonalInformation> PersonalInformations { get; set; }
    }
}
