//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Cities = new HashSet<City>();
            this.ContactInformations = new HashSet<ContactInformation>();
        }
    
        public decimal State_Id { get; set; }
        public string State_Name { get; set; }
        public bool State_Status { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<ContactInformation> ContactInformations { get; set; }
    }
}
