//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public UserRegistration()
        {
            this.ContactInformations = new HashSet<ContactInformation>();
            this.JobApplieds = new HashSet<JobApplied>();
            this.Qualifications = new HashSet<Qualification>();
            this.WorkExperiences = new HashSet<WorkExperience>();
            this.PersonalInformations = new HashSet<PersonalInformation>();
        }
    
        public decimal UserRegisteration_RegisterationId { get; set; }
        public string UserRegistration_UserName { get; set; }
        public string UserRegistration_Password { get; set; }
        public bool UserRegistration_Status { get; set; }
    
        public virtual ICollection<ContactInformation> ContactInformations { get; set; }
        public virtual ICollection<JobApplied> JobApplieds { get; set; }
        public virtual ICollection<Qualification> Qualifications { get; set; }
        public virtual ICollection<WorkExperience> WorkExperiences { get; set; }
        public virtual ICollection<PersonalInformation> PersonalInformations { get; set; }
    }
}
