//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public decimal WorkExperience_Id { get; set; }
        public decimal WorkExperience_RegisterationId { get; set; }
        public string WorkExperience_CompanyName { get; set; }
        public string WorkExperience_Designation { get; set; }
        public string WorkExperience_FromDate { get; set; }
        public string WorkExperience_ToDate { get; set; }
        public string WorkExperience_Address { get; set; }
    
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
